### ISSUE TITLE
[FR] Audio support and playback

### ISSUE THREAD

**Issue by sl1pkn07** [YomikoR/VapourSynth-Editor#11]
Hi

since VS api4 can use bestaudiosource for get audio support, is possible add into VSedit the ability for playback the audio part while playback the video?

https://www.vapoursynth.com/2020/01/audio-support-and-how-it-works/

greetings

**Comment by emako** [comment]
音声トラックの再生はホントに何とかならないのか？

**Comment by YomikoR** [comment]
Will reconsider when VS API3 is no more supported.
