### ISSUE TITLE
Installer not compatible with Win 7

### ISSUE THREAD

**Issue by EleonoreMizo** [YomikoR/VapourSynth-Editor#16]
– Win 7 64 bits
– Vapoursynth r57
– VS Editor r19 mod 4

Trying to install VSEditor with the installer doesn’t work, the installer complains that the Windows version is not supported. Manually copying the files from the archive works fine, though.

**Comment by YomikoR** [comment]
Does the installer [here](https://github.com/YomikoR/VapourSynth-Editor/releases/tag/r19-mod-5-beta) work for you?

**Comment by EleonoreMizo** [comment]
The installer works, thank you, but the program now crashes at startup, before showing any window. Same crash if I try to install it manually from the `.7z` archive.

**Comment by YomikoR** [comment]
Thanks. I can only reproduce it when there's not an existing .config file. Maybe that's why I didn't realize it at the beginning.
