### ISSUE TITLE
Bigger timeline bar?

### ISSUE THREAD

**Issue by l00tzOMG** [YomikoR/VapourSynth-Editor#21]
First of all, I really appreciate your work. Good job!

Any chance to implement a similar timeline bar present in the gundamftw fork? It is not just bigger but zoomable also. It would be really great for WQHD and UHD displays, where the original timeline bar is itsy-bitsy.

I assume this is the main commit for the relevant code is: https://bitbucket.org/gundamftw/vapoursynth-editor-2/commits/c64488c661c30f82b90674ab960222ae124e7590

Keep up the good work,
Cheers

**Comment by Ryuukishi** [comment]
I don't disagree that the current timeline bar is small especially on bigger screens, but at the same time I also feel like the timeline bar in VapourSynth Editor 2 is way too big and takes up too much of the window.

**Comment by YomikoR** [comment]
High DPI support has been much improved since Qt 6. Below is a snapshot for WQHD display at 225%.
![unknown](https://user-images.githubusercontent.com/64504948/146627891-fd9a7003-7fb3-431c-a53d-a9db922cfea3.png)
Do you need further adjustments?

**Comment by l00tzOMG** [comment]
Which version is this? Or is this only because of DPI scaling is set to 225%?

I'm using mod4 and on a 4k display the height of the timeline bar (bar + numbers on top) is almost the same as the height of the cursor. This is definately small for me and hard to position. I agree, that in the "2" fork it is oversized and the optimum would be inbetween. I'm using DPI 150% BTW. See attached screenshot.

<img width="1920" alt="Screenshot 2021-12-18 105408" src="https://user-images.githubusercontent.com/52856431/146647357-3a95649e-0a33-47ca-b1ab-c50b6b00427d.png">

**Comment by YomikoR** [comment]
> Which version is this? Or is this only because of DPI scaling is set to 225%?

Forgot to upload. You may take a look at the recent pre-release.

**Comment by l00tzOMG** [comment]
Thanks, it's slightly bigger now. However, I would be happy with the ~twice of its current size.

<img width="1920" alt="Screenshot 2021-12-18 185326" src="https://user-images.githubusercontent.com/52856431/146658648-60d4273c-6fc7-448c-80b3-2b53f9d219a1.png">

**Comment by YomikoR** [comment]
I'll try to find a workaround. Maybe ending up with a global scaling factor.
For now another option is `QT_SCALE_FACTOR=1.5 ./vsedit.exe` (for Qt 5 builds as well).
For coordination between two or more monitors (with different scaling ratio) I would just give up.

**Comment by l00tzOMG** [comment]
Thank you for your efforts.

**Comment by YomikoR** [comment]
Sorry, I'm really dumb for this UI stuff.

If you would like to create a *shortcut* to launch vsedit.exe at a given (global) scaling factor (based on existing DPI), you may fill the target as
```
C:\Windows\System32\cmd.exe /c "SET QT_SCALE_FACTOR=1.5 && START /D ^"C:\Program Files\VapourSynth Editor^" vsedit.exe"
```
The path may also be relative from where you visit.

**Comment by l00tzOMG** [comment]
Thanks, it's not perfect, but a lot better now!
