### ISSUE TITLE
Issue with RGB preview ?dither

### ISSUE THREAD

**Issue by pdr0github** [YomikoR/VapourSynth-Editor#22]
Solid color bars , running the color picker along a bar, the YUV read values are uniform correct values. But the converted display RGB values vary on the same bar almost like a dither pattern applied

You can use vapoursynth-colorbars , or if it's easier download
https://www.mediafire.com/file/imbdltobvm9w7rk/vapoursynth_colorbars_YUV420P8_noconv.mp4/file

clip = core.lsmas.LibavSMASHSource(r'vapoursynth_colorbars_YUV420P8_noconv.mp4')
clip.set_output()

Affects r19-mod-3 , mod-4, and mod-5-beta2 (did not test others)

Original r19 and vsedit2 do not exhibit the issue

**Comment by YomikoR** [comment]
It's true, and I'm not going to change it back.

To circumvent dithering, you may resample the clip to RGB24 (or RGB30 if 10-bit color depth is supported on your platform) using VS internal resizers in your script.
