### ISSUE TITLE
Vapoursynth R58 portable compatiblity?

### ISSUE THREAD

**Issue by Selur** [YomikoR/VapourSynth-Editor#26]
I deleted %LOCALAPPDATA%/vsedit.config and extracted VapourSynth-Editor-r19-mod-5.1-x86_64-Qt6.7z into the Vapoursynth folder, but on startup I get: "Failed to initialize VapourSynth environment!" (two times)
Seems like r19-mod-5.1 is not compatible with portable Vapoursynth R58, or am I missing something?

**Comment by YomikoR** [comment]
Did you test with Python 3.10?

**Comment by Selur** [comment]
No, I use Python 3.9.7 which worked fine so far.
Does the editor require 3.10 for some reason, afaik Vapoursynth just aside from 3.9 now also suppoert 3.8 and 3.10, but it does not require 3.10 or 3.9

**Comment by YomikoR** [comment]
> -> using Python 3.10 works, but why is it needed?
https://github.com/vapoursynth/vapoursynth/pull/805#issuecomment-941017937

**Comment by Selur** [comment]
Ah, didn't know that. Thanks for clearing that up. :)
