### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by hooke007** [YomikoR/VapourSynth-Editor#27]
this mod ignore the Paths I set (from the menu), it only use python&vapoursynth which are listed in the PATH environment variable.

edit: I can reproduce it by upstream's version.

**Comment by YomikoR** [comment]
Try if you can run vspipe as you wish in your environment. I think [in the portable mode](https://github.com/vapoursynth/vapoursynth/blob/8d87e7dd523331efcfd2558870c649460a8c46ef/src/vsscript/vsscript.cpp#L81-L82) you have to keep VS and Python in the same directory.

**Comment by hooke007** [comment]
> keep VS and Python in the same directory.

It did. The python and vs in the environment variable are also set in the same dir. But vseditor could only use environment variable.
Alternatively, is there any way to ignore user’s PATH environment variable.(only read the dir via menu’s settings)

**Comment by YomikoR** [comment]
![unknown](https://user-images.githubusercontent.com/64504948/162398694-360c0fd7-fb99-4d6a-90df-3e1412c361c2.png)
The editor searches in PATH for vsscript.dll, then in the registry, then the one in the settings (using full path is also okay).

It would be a different story though if you have one instance of VS in PATH but you want the editor to find another one.

**Comment by hooke007** [comment]
I see. PATH's python is used by another program in my device, while VSE treated the ‘settings dir’ as the lowest priority. I thought I could use VSE truly 'independently'. Now I temporarily deleted the PATH to avoid the issue.
