### ISSUE TITLE
Save snapshot

### ISSUE THREAD

**Issue by daomengRen** [YomikoR/VapourSynth-Editor#29]
hi,is it possible to template the file name of the snapshot through template settings when saving snapshot?

**Comment by YomikoR** [comment]
I will think about adding it next to the file drop templates.

**Comment by daomengRen** [comment]
thanks

**Comment by daomengRen** [comment]
by the way, do you know where there are detailed instructions on how to use it? I'm a newbie in coding, such as the file drop templates you just mentioned, I even just knew about this function, but I don't know what this template is for what

**Comment by YomikoR** [comment]
Sorry, there has never been a manual.

By default, if you drag a video file `/path/to/video` to the editor window, there will be a new line showing `r'/path/to/video'`. With the file drop template you can customize the texts to be added.
![unknown](https://user-images.githubusercontent.com/64504948/165257899-3fcdcf51-4985-4f6d-92cf-3c09bde86cf9.png)

**Comment by daomengRen** [comment]
Wow, this is a very nice feature, thanks for your example, I'm looking forward to the save snapshot template even more, thanks again
