### ISSUE TITLE
Show version in terminal

### ISSUE THREAD

**Issue by davidak** [YomikoR/VapourSynth-Editor#38]
I want to create an integration test to check if the packaged program has the right version. For that i need a way to output the version in terminal.

Most CLI programs have a parameter like:

`vsedit --version`

or

`vsedit version`

but both lead to error.

![Screenshot from 2022-09-09 17-52-21](https://user-images.githubusercontent.com/91113/189391121-f8b66b4f-f702-4d53-8f89-faf95a9e79d8.png)

example:

```
[nix-shell:~/code/nixpkgs]$ git --version
git version 2.36.2
```

Could you implement that feature?

**Comment by YomikoR** [comment]
Sorry, versioning is hard on a personal fork.

**Comment by davidak** [comment]
The version format is uncommon, but not a problem for us. I ask for an option to show the version in terminal and exit.

I'm not sure if that fits for GUI programs and if it's a sane thing to ask. Do you have an opinion?

Otherwise we would need a GUI integration test, which can also be useful to make sure the GUI starts.

**Comment by YomikoR** [comment]
I see. The version string can always be found in README. Is that already what you need?

**Comment by davidak** [comment]
It could happen that a project forgets to update the readme, so that is not reliable.

I asked in social media if a `--version` option makes sense for GUI programs, and everyone said yes. Many popular open source gui programs have that.

https://chaos.social/@davidak/108985098142325538

Would you implement that?

**Comment by YomikoR** [comment]
Please let me know if the latest release doesn't work as expected in your toolset.

**Comment by davidak** [comment]
It works perfectly! We will update the package in nixpkgs.

```
[davidak@gaming:~/code/nixpkgs]$ /nix/store/8sa86nrkyi01s516j0ng43wxwx6zs06k-vapoursynth-editor-19-mod-5.4-with-plugins/bin/vsedit --version
VapourSynth Editor R19-mod-5.4
```

Thank you!
