### ISSUE TITLE
Crashes when removing removing file drop templates

### ISSUE THREAD

**Issue by Ryuukishi** [YomikoR/VapourSynth-Editor#4]
How to reproduce:

1. Navigate to file drop templates. 
2. Delete an item from the list
3. Click 'Save all'

This causes it to crash 100% of the time. I'm running Windows 10.

**Comment by YomikoR** [comment]
Sorry, I didn't figure out how to make it crash. Could you please run in portable mode and upload your `vsedit.config`?

**Comment by YomikoR** [comment]
Thanks for reporting. I still cannot reproduce in the same way as you suggested but I'm sure something is wrong.

**Comment by YomikoR** [comment]
I'm not sure when it will be fixed. For now you may (switch to portable mode,) edit the config file (and switch back)
```
[drop_file_templates]
clip\mask_list=*.mkv, *.mp4,
clip\template="clip = core.ffms2.Source(r'{f}')"
clip2\mask_list=......
clip2\template=......
```

**Comment by YomikoR** [comment]
[vsedit.zip](https://github.com/YomikoR/VapourSynth-Editor/files/7212184/vsedit.zip)
Does it work for you?

**Comment by Ryuukishi** [comment]
Sorry for the long reply, r19-mod-3 fixes the crash. Thanks!
