### ISSUE TITLE
SIGILL, Illegal instruction on Arch Linux

### ISSUE THREAD

**Issue by krakoi** [YomikoR/VapourSynth-Editor#41]
Hi!

vsedit doesn't even start on my Arch Linux. I tried to run it in debug mode (gdb), I get this immediately after `run`:

```
Thread 1 "vsedit" received signal SIGILL, Illegal instruction.
0x00005555555fdcb9 in ScriptEditor::ScriptEditor (this=this@entry=0x555555757f60, a_pParent=<optimized out>) at ../../vsedit/src/script_editor/script_editor.cpp:55
55		, m_pContextMenu(nullptr)
```

**Comment by YomikoR** [comment]
Thanks for reporting. Did you build the binaries by your self, or did you install from AUR?

**Comment by krakoi** [comment]
@YomikoR 
I got the issue originally with the AUR package, but I have the same result if I clone this repo and build it manually (using the build steps from https://github.com/YomikoR/VapourSynth-Editor/blob/master/BUILDING ).

**Comment by YomikoR** [comment]
I have a PC with Manjaro installed so I haven't yet tested on Arch. Things work with kernel 6.0.11, gcc 12.2.0, qt5-base 5.15.7+kde+r176-1 as of today. May I know how you built yours? Also could you check the result of `ldd vsedit` for dependencies?

**Comment by marillat** [comment]
@krakoi which architecture are you using ? Also which CPU ?

**Comment by krakoi** [comment]
@marillat Sorry about responding so late, I didn't have the time then and I completely forgot about it.

I looked into it again and actually it turned out to be an error on my side. I fixed the compiler flags and https://aur.archlinux.org/packages/vapoursynth-editor seems to be working now! Ticket can be closed!
