### ISSUE TITLE
Weird scaling

### ISSUE THREAD

**Issue by Mr-Z-2697** [YomikoR/VapourSynth-Editor#48]
Doesn't happen in 5.4
![2023-02-12_230336](https://user-images.githubusercontent.com/74594146/218320815-3351fa45-8993-4696-b267-d06eeeef4668.png)

**Comment by Mr-Z-2697** [comment]
This is what 5.4 looks like
![2023-02-12_234014](https://user-images.githubusercontent.com/74594146/218320946-ab48df4d-a7cd-4ce6-acb0-20c9e4201c13.png)

**Comment by YomikoR** [comment]
I guess the reason is you picked the Qt 5 build.

**Comment by Mr-Z-2697** [comment]
> I guess the reason is you picked the Qt 5 build.

I checked Qt dlls and their name start with Qt6.

**Comment by YomikoR** [comment]
Okay, I think I know what's going on.

**Comment by YomikoR** [comment]
The issue was likely caused by regression in Qt 6.4.1.
[VSEditor-4311c61-Qt6.4.2.zip](https://github.com/YomikoR/VapourSynth-Editor/files/10717995/VSEditor-4311c61-Qt6.4.2.zip)
