### ISSUE TITLE
encode preset header is not loaded correctly

### ISSUE THREAD

**Issue by theChaosCoder** [YomikoR/VapourSynth-Editor#5]
When opening the encode window the Header is always set to "no header" even though it was saved as "Y4M".

![image](https://user-images.githubusercontent.com/3579830/135340015-d7e0c3be-8f47-4924-8864-8c8ddc061c37.png)

**Comment by YomikoR** [comment]
In case you need it immediately
[vsedit_exe_c1c7eb6.zip](https://github.com/YomikoR/VapourSynth-Editor/files/7258913/vsedit_exe_c1c7eb6.zip)
