### ISSUE TITLE
Encode video does not work

### ISSUE THREAD

**Issue by jones1913** [YomikoR/VapourSynth-Editor#50]
Hey, encode video does not work for me, error message in log is: `Encoder wouldn't start.`
System is Manjaro Linux.

I suspect it has to do with process.start signature:
https://github.com/YomikoR/VapourSynth-Editor/blob/ccd9b755e0e39af73900d0f2f337289511c741d6/common-src/jobs/job.cpp#L1345

It works when I replace it with:
`m_process.start(executable, decodedArguments.split(" "));`

but only if target path contains no spaces. So I guess a proper fix is required...

**Comment by YomikoR** [comment]
Could you check if the latest commit works for you?

**Comment by jones1913** [comment]
Yeah it works now, thank you.
