### ISSUE TITLE
Failed to initialize VapourSynth environment

### ISSUE THREAD

**Issue by dnjulek** [YomikoR/VapourSynth-Editor#7]
```
2021-09-30 01:07:42.541
Failed to initialize VapourSynth environment!
Failed to initialize VapourSynth environment!
```
I have tried mod-2 and mod-3, neither worked with my VS R55 and now R56.
vapoursynth-preview I am using misakikasumi's fork, works fine.

EDIT:  It seems to recognize the plugins folder at least
![](https://i.imgur.com/a4WJgcO.png)

**Comment by YomikoR** [comment]
Does vspipe work in the same environment?

**Comment by dnjulek** [comment]
Yes, no problem with vspipe.

**Comment by dnjulek** [comment]
Fixed after removing `C:\mingw64\bin` from path

**Comment by YomikoR** [comment]
Good to hear that.
I guess you have `vapoursynth.dll` well configured (allowing finding plugins and letting vsp work), but something went wrong for `vsscript.dll`.

**Comment by dnjulek** [comment]
Yes, my mingw64 folder has some API3 files from when I compiled the descale dll.
